server {
    listen 80;
    server_name localhost;

    # Directorio base donde estaran nuestros archivos
    root /usr/share/nginx/html;
    index index.html;

    # === RUTEO SPA / BÁSICO ===
    location / {
        try_files $uri $uri/ /index.html;
    }

    # === OPTIMIZACIÓN DE RENDIMIENTO (GZIP) ===
    # Comprime los archivos antes de enviarlos al cliente, 
    # crucial para la velocidad en produccion.
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_disable "MSIE [1-6]\.";

    # === CACHÉ DE ARCHIVOS ESTÁTICOS ===
    # Instruye al navegador a guardar en caché CSS y JS
    location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}
